public_route_data_controller:
    resource: "@WioEdkBundle/Controller/PublicRouteDataController.php"
    type:     annotation
public_edk_error_controller:
    resource: "@WioEdkBundle/Controller/PublicEdkErrorController.php"
    type:     annotation
public_message_form_controller:
    resource: "@WioEdkBundle/Controller/PublicMessageFormController.php"
    type:     annotation
public_registration_form_controller:
    resource: "@WioEdkBundle/Controller/PublicRegistrationFormController.php"
    type:     annotation
area_note_controller:
    resource: "@WioEdkBundle/Controller/AreaNoteController.php"
    type:     annotation
edk_registration_controller:
    resource: "@WioEdkBundle/Controller/RegistrationSettingsController.php"
    type:     annotation
area_message_controller:
    resource: "@WioEdkBundle/Controller/AreaMessageController.php"
    type:     annotation
area_participant_controller:
    resource: "@WioEdkBundle/Controller/AreaParticipantController.php"
    type:     annotation
area_stats_participant_controller:
    resource: "@WioEdkBundle/Controller/AreaStatsParticipantController.php"
    type:     annotation
edk_route_controller:
    resource: "@WioEdkBundle/Controller/RouteController.php"
    type:     annotation
project_stats_route_controller:
    resource: "@WioEdkBundle/Controller/ProjectStatsRouteController.php"
    type:     annotation
project_stats_participant_controller:
    resource: "@WioEdkBundle/Controller/ProjectStatsParticipantController.php"
    type:     annotation
