imports:
    - { resource: ../../../../../app/config/parameters.yml }

parameters:
    extensions.class: Cantiga\CoreBundle\Api\ExtensionPoints\ExtensionPoints
    locale_provider.class: Cantiga\Metamodel\LocaleProvider
    user_provider.class: Cantiga\CoreBundle\Repository\AuthRepository
    transaction.class: Cantiga\Metamodel\Transaction
    time_formatter.class: Cantiga\Metamodel\TimeFormatter
    database_settings_storage.class: Cantiga\CoreBundle\Settings\DatabaseSettingsStorage
    project_settings.class: Cantiga\CoreBundle\Settings\ProjectSettings
    archived_project_repository.class: Cantiga\CoreBundle\Repository\ArchivedProjectRepository
    language_repository.class: Cantiga\CoreBundle\Repository\LanguageRepository
    project_repository.class: Cantiga\CoreBundle\Repository\ProjectRepository
    admin_membership_repository.class: Cantiga\CoreBundle\Repository\AdminMembershipRepository
    area_memberlist_repository.class: Cantiga\CoreBundle\Repository\AreaMemberListRepository
    group_membership_repository.class: Cantiga\CoreBundle\Repository\GroupMembershipRepository
    project_group_membership_repository.class: Cantiga\CoreBundle\Repository\ProjectGroupMembershipRepository
    project_membership_repository.class: Cantiga\CoreBundle\Repository\ProjectMembershipRepository
    project_memberlist_repository.class: Cantiga\CoreBundle\Repository\ProjectMemberListRepository
    UserRegistrationRepository.class: Cantiga\CoreBundle\Repository\UserRegistrationRepository
    user_area_request_repository.class: Cantiga\CoreBundle\Repository\UserAreaRequestRepository
    project_area_request_repository.class: Cantiga\CoreBundle\Repository\ProjectAreaRequestRepository
    project_group_repository.class: Cantiga\CoreBundle\Repository\ProjectGroupRepository
    project_area_membership_repository.class: Cantiga\CoreBundle\Repository\ProjectAreaMembershipRepository
    app_text_repository.class: Cantiga\CoreBundle\Repository\AppTextRepository
    app_mail_repository.class: Cantiga\CoreBundle\Repository\AppMailRepository
    project_membership_loader.class: Cantiga\CoreBundle\Entity\Membership\ProjectMembershipLoader
    group_membership_loader.class: Cantiga\CoreBundle\Entity\Membership\GroupMembershipLoader
    area_membership_loader.class: Cantiga\CoreBundle\Entity\Membership\AreaMembershipLoader
    ui_block.class: Cantiga\CoreBundle\Block\UiBlock
    block_launcher.class: Cantiga\CoreBundle\Block\BlockLauncher
    area_membership_repository.class: Cantiga\CoreBundle\Repository\AreaMembershipRepository
    project_area_status.class: Cantiga\CoreBundle\Repository\ProjectAreaStatusRepository
    project_territory.class: Cantiga\CoreBundle\Repository\ProjectTerritoryRepository
    cantiga.controller.exception.class: Cantiga\CoreBundle\Controller\ExceptionController
    area_per_status_stats.class: Cantiga\CoreBundle\Statistics\AreasPerStatusStats
    db_files: %kernel.root_dir%/../db/
    targetFileDirectory: %kernel.root_dir%/../uploads/
    
services:
    cantiga.extensions:
        class:     "%extensions.class%"
        arguments: ["@service_container"]
    cantiga.locale:
        class:     "%locale_provider.class%"
        arguments: ["%locale%"]
    cantiga.user_provider:
        class:     Cantiga\CoreBundle\Repository\AuthRepository
        arguments: ["@database_connection"]
    cantiga.blocks:
        class:     "%block_launcher.class%"
        arguments: ["@service_container"]
    cantiga.transaction:
        class:     "%transaction.class%"
        arguments: ["@database_connection"]
    cantiga.time:
        class:     "%time_formatter.class%"
        arguments: ["%defaultTimezone%"]
    cantiga.importer:
        class:     Cantiga\CoreBundle\Services\ImporterService
        arguments: ["@cantiga.user.membership.storage", "@security.token_storage", "@translator"]
    cantiga.files:
        class:     Cantiga\Metamodel\FileRepository
        arguments: ["%targetFileDirectory%"]
    cantiga.roles:
        class:     Cantiga\Metamodel\MembershipRoleResolver
    cantiga.security.recaptcha:
        class:     Cantiga\CoreBundle\Services\RecaptchaService
        arguments: ["@=container.getParameter('cantiga')['recaptcha']['siteKey']", "@=container.getParameter('cantiga')['recaptcha']['secretKey']"]
    cantiga.project.settings.database_storage:
        class:     "%database_settings_storage.class%"
        arguments: ["@database_connection"]
    cantiga.project.settings:
        class:     "%project_settings.class%"
        arguments: ["@cantiga.project.settings.database_storage"]
    cantiga.controller.exception:
        class:     "%cantiga.controller.exception.class%"
        arguments: ["@twig", "%kernel.debug%"]
    cantiga.core.block.ui:
        class:     "%ui_block.class%"
        arguments: ["@cantiga.workspace_listener", "@event_dispatcher", "@twig", "@security.token_storage", "@translator"]
    cantiga.core.area_request_flow:
        class:     Cantiga\CoreBundle\Repository\Utils\AreaRequestFlow
        arguments: ["@cantiga.core.repo.user_area_request", "@cantiga.user.repo.contact"]
    cantiga.core.repo.place.project:
        class:     Cantiga\CoreBundle\Repository\Place\ProjectLoader
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.place-loader, type: Project }
    cantiga.core.repo.place.group:
        class:     Cantiga\CoreBundle\Repository\Place\GroupLoader
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.place-loader, type: Group }
    cantiga.core.repo.place.area:
        class:     Cantiga\CoreBundle\Repository\Place\AreaLoader
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.place-loader, type: Area }
    cantiga.core.repo.language:
        class:     "%language_repository.class%"
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.admin_user:                                                                                                                                                       
        class:     Cantiga\CoreBundle\Repository\AdminUserRepository                                                                                                                                     
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@cantiga.time", "@cantiga.roles"]
    cantiga.core.repo.project:                                                                                                                                                     
        class:     Cantiga\CoreBundle\Repository\ProjectRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@cantiga.time", "@event_dispatcher", "@cantiga.project.settings.database_storage"]
    cantiga.core.repo.archived_project:                                                                                                                                                     
        class:     Cantiga\CoreBundle\Repository\ArchivedProjectRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@cantiga.time"]
    cantiga.core.repo.user_registration:                                                                                                                                                
        class:     Cantiga\CoreBundle\Repository\UserRegistrationRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@security.encoder_factory", "@cantiga.time"]
    cantiga.core.repo.user_dashboard:
        class:     Cantiga\CoreBundle\Repository\UserDashboardRepository
        arguments: ["@database_connection"]
    cantiga.core.repo.user_area_request:
        class:     Cantiga\CoreBundle\Repository\UserAreaRequestRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@cantiga.time", "@security.token_storage"]
    cantiga.core.repo.project_area_request:
        class:     Cantiga\CoreBundle\Repository\ProjectAreaRequestRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@cantiga.time", "@event_dispatcher", "@cantiga.roles"]
    cantiga.core.repo.project_group:
        class:     Cantiga\CoreBundle\Repository\ProjectGroupRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher"]
    cantiga.core.repo.area_mgmt:
        class:     Cantiga\CoreBundle\Repository\AreaMgmtRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@cantiga.roles"]
    cantiga.core.repo.project_area_status:
        class:     Cantiga\CoreBundle\Repository\ProjectAreaStatusRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.project_group_category:
        class:     Cantiga\CoreBundle\Repository\ProjectGroupCategoryRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.project_territory:
        class:     Cantiga\CoreBundle\Repository\ProjectTerritoryRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.text:
        class:     Cantiga\CoreBundle\Repository\AppTextRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.mail:
        class:     Cantiga\CoreBundle\Repository\AppMailRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    cantiga.core.repo.statistics:                                                                                                                               
        class:     Cantiga\CoreBundle\Repository\CoreStatisticsRepository
        arguments: ["@database_connection"]
        tags:
            - { name: kernel.event_listener, event: cantiga.area-request.created, method: onAreaRequestStatusChange }
            - { name: kernel.event_listener, event: cantiga.area-request.verification, method: onAreaRequestStatusChange }
            - { name: kernel.event_listener, event: cantiga.area-request.approved, method: onAreaRequestStatusChange }
            - { name: kernel.event_listener, event: cantiga.area-request.revoked, method: onAreaRequestStatusChange }
    cantiga.core.filter.area:
        class: Cantiga\CoreBundle\Filter\AreaFilter
        arguments: ["@cantiga.core.repo.project_area_status", "@cantiga.core.repo.project_group", "@cantiga.core.repo.project_group_category", "@cantiga.core.repo.project_territory"]
    cantiga.core.filter.area_request:
        class: Cantiga\CoreBundle\Filter\AreaRequestFilter
        arguments: ["@translator", "@cantiga.core.repo.project_territory"]

    cantiga.core.stats.area_per_status:
        class:     "%area_per_status_stats.class%"
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.extension, point: core.stats.area }
    cantiga.core.stats.area_requests_over_time:
        class:     Cantiga\CoreBundle\Statistics\AreaRequestsOverTimeStats
        arguments: ["@database_connection", "@cantiga.core.repo.statistics", "@translator"]
        tags:
            - { name: cantiga.extension, point: core.stats.area }
    cantiga.core.dashboard.text:
        class:     Cantiga\CoreBundle\Extension\DashboardTextExtension
        arguments: ["@cantiga.core.repo.text", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.user.central }
            - { name: cantiga.extension, point: core.dashboard.admin.central }
            - { name: cantiga.extension, point: core.dashboard.project.right }
            - { name: cantiga.extension, point: core.dashboard.group.right }
            - { name: cantiga.extension, point: core.dashboard.area.right }
    cantiga.core.dashboard.recent_comments:
        class:     Cantiga\CoreBundle\Extension\DashboardChatExtension
        arguments: ["@cantiga.core.repo.project_area_request", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.project.central }
    cantiga.core.dashboard.recent_requests:
        class:     Cantiga\CoreBundle\Extension\DashboardRequestExtension
        arguments: ["@cantiga.core.repo.project_area_request", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.project.central }
    cantiga.core.dashboard.area_summary:
        class: Cantiga\CoreBundle\Extension\AreaSummaryExtension
        arguments: ["@templating", "@cantiga.user.membership.storage"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.area.top }
    cantiga.core.dashboard.project_summary:
        class: Cantiga\CoreBundle\Extension\ProjectSummaryExtension
        arguments: ["@cantiga.core.repo.statistics", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.project.top }
    cantiga.core.dashboard.admin_summary:
        class: Cantiga\CoreBundle\Extension\AdminSummaryExtension
        arguments: ["@cantiga.core.repo.statistics", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.admin.top }
    cantiga.theme_listener:
        class: Cantiga\CoreBundle\EventListener\UiListener
        arguments: ["@security.token_storage", "@security.authorization_checker", "@router", "@cantiga.workspace_listener", "@cantiga.user.membership.storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: cantiga.ui.user, method: showUser }
            - { name: kernel.event_listener, event: cantiga.ui.help, method: showHelpPages }
            - { name: kernel.event_listener, event: cantiga.ui.workspaces, method: showWorkspaces }
            - { name: kernel.event_listener, event: cantiga.ui.tasks, method: showTasks }
            - { name: kernel.event_listener, event: cantiga.ui.breadcrumbs, method: showBreadcrumbs }
            - { name: kernel.event_listener, event: cantiga.ui.projects, method: showPlaces }
            - { name: kernel.event_listener, event: cantiga.workspace.general, method: showMenu }
    cantiga.workspace_listener:
        class: Cantiga\CoreBundle\EventListener\WorkspaceListener
        arguments: ["@security.authorization_checker", "@security.token_storage", "@cantiga.user.membership.finder", "@cantiga.project.settings"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onControllerSelected }
            - { name: kernel.event_listener, event: cantiga.workspace.user, method: onUserWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.area, method: onAreaWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.group, method: onGroupWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.project, method: onProjectWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.admin, method: onAdminWorkspace }
    cantiga.general_listener:
        class: Cantiga\CoreBundle\EventListener\GeneralListener
        arguments: ["@security.authorization_checker", "@security.token_storage", "@cantiga.transaction", "@session", "@cantiga.time", "@translator", "@cantiga.locale"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    cantiga.error_listener:
        class: Cantiga\CoreBundle\EventListener\ErrorListener
        arguments: ["@security.http_utils"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    cantiga.core.project_listener:
        class: Cantiga\CoreBundle\EventListener\ProjectListener
        arguments: ["@database_connection"]
        tags:
            - { name: kernel.event_listener, event: cantiga.project.created, method: onProjectCreated }
    cantiga.twig_extension:
        class:     Cantiga\CoreBundle\Twig\CantigaExtension
        arguments: [ "@cantiga.workspace_listener", "@cantiga.time", "@cantiga.user.membership.storage", "@router", "@cantiga.blocks"]
        tags:
            - { name: twig.extension }
    cantiga.bootstrap_form_extension:
        class:     Cantiga\CoreBundle\Twig\BootstrapFormExtension
        arguments: ["glyphicon", "span"]
        tags:
            - { name: twig.extension }
    cantiga.core.form.basic_area_request:
        class:     Cantiga\CoreBundle\CustomForm\BasicAreaRequestModel
        tags:
            - { name: cantiga.extension, point: core.form.area-request, module: core, description: "Basic area request form" }
    cantiga.core.form.basic_area:
        class:     Cantiga\CoreBundle\CustomForm\BasicAreaModel
        tags:
            - { name: cantiga.extension, point: core.form.area, module: core, description: "Basic area form" }
    cantiga.core.form.default_area_request:
        class:     Cantiga\CoreBundle\CustomForm\DefaultAreaRequestModel
        tags:
            - { name: cantiga.extension, point: core.form.area-request, module: core, description: "Default area request form" }
    cantiga.core.form.default_area:
        class:     Cantiga\CoreBundle\CustomForm\DefaultAreaModel
        tags:
            - { name: cantiga.extension, point: core.form.area, module: core, description: "Default area form" }