imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
        
doctrine:
    dbal:
        driver:   "%test_database_driver%"
        host:     "%test_database_host%"
        port:     "%test_database_port%"
        dbname:   "%test_database_name%"
        user:     "%test_database_user%"
        password: "%test_database_password%"
        charset:  UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
